#eweqw
version: '3'

services:
  server:
    container_name: personal-website
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/personal-website
    restart: always
    ports:
      - 3000:3000
